### ISSUE TITLE
Link to slideshow not working

### ISSUE THREAD

**Issue by Flamefire** [psteinb/pain-of-performance-portability#1]
It just leads to an error page. Probably setting forgotten?

**Comment by psteinb** [comment]
nope, but the talk is simply not finished (yet). ;) Stay tuned.
Peter

**Comment by psteinb** [comment]
fixed, https://psteinb.github.io/pain-of-performance-portability/#/

**Comment by psteinb** [comment]
even though there are still some slides to come. feel free to close the issue and thanks for reporting.
